### ISSUE TITLE
Implement `deb-configure-builder`

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-debian#16]
Given a `builder` dataset it configures a "recipe" for creating a build environment. This recipe will use a specific technology (like singularity), but the API of this command should not be needlessly specific to a particular implementation (think qemu based setups, ...)

**Comment by adswa** [comment]
Can I envision this as a datalad-installer-like API, with, e.g., an ``-m/--method`` parameter for Singularity/Docker/qemu/...?

And also a clarifying question about qemu, because I have never heard of it - it doesn't look like a system easily usable with ``containers-run``, right? Could one wrap up a qemu-like setup in a script and execute it in a ``datalad run`` command?

**Comment by mih** [comment]
Thx for asking! I think we should not worry about a concrete API for different (non-singularity) methods now, and also not about a selection API. Indeed, `datalad containers-run` would not help here (for now). What I wanted to say (and only that) is that the currently needed API should not blindly assume singularity or needlessly adopt singularity terminology and semantics. Other than that, I firmly believe that we should aim straight for singularity, and only that (for now).

**Comment by adswa** [comment]
thanks for clarifying.

**Comment by mih** [comment]
https://github.com/psychoinformatics-de/datalad-debian/issues/12#issuecomment-1133233807 documents the state of the implementation, which addresses the current needs.
