### ISSUE TITLE
Implement `deb-update-distribution`

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-debian#20]
Given a `distribution` dataset, pull updates for one, many or all package subdatasets, and save a new state of the distribution. This may also involve a metadata extraction and aggregation step.

**Comment by adswa** [comment]
I'm playing with implementing this, but I am not 100% sure of the intended functionality. As I don't think that package subdatasets are hosted elsewhere (I could be wrong here, please correct me), the only sensible "update" I can think of involves a recursive update of each specified packages source repository subdataset and a rebuild of this package. Is how others envision this command, too?

I think this is also related to #10, because if there is a dedicated location for all most recent packages in the distribution dataset, ``deb-update-distribution``'s job would probably also involve adding the most recent package versions, right?

**Comment by aqw** [comment]
I don't know the implications if the subdatasets are hosted elsewhere, so I don't see how it would be change things.

But what you described makes sense to me. Check all package subdatasets, update them to latest, register everything in the distribution dataset (with whatever metadata magic is currently planned).

As for updating a `packages-latest`, it's not clear to me the necessity of that. It really depends how `reprepro` ends up consuming this dataset. I don't see a use-case for having exclusively the latest packages, except for reprepo /  the mirrors themselves. Perhaps mih has something in mind though.

**Comment by mih** [comment]
Just came around to this again. I think with the current concept we arrived at this is pretty much a

```
datalad update --how ff-only --recursive --recursion-limit 1 -- packages
```

The only thing missing is the convenience of going through any and all subdatasets, whether or not they are present locally.

Why is this command needed at all? With the following workflow it is NOT needed:

1. clone a distribution dataset
(1b). optionally re-bootstrap its builder dataset
2. pick the package subdataset to update, and `get` it
3. update a `dsc`, or build binary packages
4. save distribution dataset and push back the updates to all datasets

However, this workflow means that whoever is doing a package dataset update is also interested in updating the associated distribution dataset. One could imagine that there could be a volunteer that is willing to pick a package dataset only, and push a new source package version into it.

Having written this down, I think this use case can be ignored. Whoever is generating a DSC to include in a package dataset, can be considered a package maintainer. A typical goal for a package maintainer is the inclusion of their work in a distribution. For this to happen, they have to update the distribution. In a traditional setup there would be a gate-keeping problem, but in our decentralized world anyone can update a source package -- the question is whether or not their update is merged into the mainline (clone).

Following that conclusion, we can close this issue.
