### ISSUE TITLE
Builder recipe with 3rd-party package archive support

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-debian#33]
When building backports that require backports these intermediate packages need to go somewhere, to be available for subsequent builds. Typically, this would be an unofficial package archive.

We need a recipe that can do this.

IMHO it would be useful to not complicate the default recipe, but add another one.

To avoid duplication, the runscript implementation can also be taken out of the recipe and pieces copied in from the host (this package's sources) when bootstrapping the builder.

**Comment by aqw** [comment]
IMO, either Debian Backports or NeuroDebian are a good example for this. (One or the other, not both).

Ideally, the config would be placed in a file under `/etc/apt/sources.list.d/` rather than added to `/etc/apt/sources.list` (though that is also ok, and not a blocker).

Backports (i.e. `/etc/apt/sources.list.d/debian-backports.list`):
```
deb http://debian.mirror.htc.inm7.de/debian buster-backports main contrib non-free
deb-src http://debian.mirror.htc.inm7.de/debian buster-backports main contrib non-free
```

NeuroDebian (i.e. `/etc/apt/sources.list.d/neurodebian.list`):
```
deb http://neurodebian.mirror.htc.inm7.de/debian buster main contrib non-free
deb-src http://neurodebian.mirror.htc.inm7.de/debian buster main contrib non-free

deb http://neurodebian.mirror.htc.inm7.de/debian data main contrib non-free
deb-src http://neurodebian.mirror.htc.inm7.de/debian data main contrib non-free
```

**Comment by mih** [comment]
The pattern outlined in https://github.com/psychoinformatics-de/datalad-debian/pull/108 is a candidate to implement this without having to provide an independent recipe template.
