### ISSUE TITLE
`www/` vs `debian/` in the reprepro dataset?

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-debian#69]

**Comment by aqw** [comment]
I've been using `www/` for awhile now. I like this, because it's quite explicit about the published nature of the dir (even though apt repos can be accessed via methods other than http/s).

However, I do also like `debian/`, as it is a common convention to serve apt archives from that URL. My primary dislike of this dir name is that it's quite ambiguous if one is unaware of this convention.

I think both are good choices, but I lean towards `www/` as it's more obvious (though deviant).
